/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface DashboardElementContainer {
    'ElementTitle': string;
  }
  interface DashboardElementContainerAttributes extends StencilHTMLAttributes {
    'ElementTitle'?: string;
  }

  interface TernaryGraph {
    'OutlineHex': string;
    'aHex': string;
    'abAxisLabel': string;
    'abFadeName': string;
    'abFadeURL': string;
    'abMixHex': string;
    'abMixOpacity': string;
    'abTextPathHref': string;
    'abTextPathName': string;
    'acAxisLabel': string;
    'acTextPathHref': string;
    'acTextPathName': string;
    'axisLabelFontSize': number;
    'bHex': string;
    'bcAxisLabel': string;
    'bcTextPathHref': string;
    'bcTextPathName': string;
    'cFadeEndHex': string;
    'cFadeEndOpacity': string;
    'cFadeName': string;
    'cFadeURL': string;
    'cHex': string;
    'circleRadius': number;
    'corners': {"A":{"X","Y"}, "B":{"X","Y"},"C":{"X","Y"}};
    'hectagonHex': string;
    'recordArray': Array<{"A","B","C","X"?,"Y"?,"Z"?,"Label"}>;
    'showHectagon': boolean;
  }
  interface TernaryGraphAttributes extends StencilHTMLAttributes {
    'OutlineHex'?: string;
    'aHex'?: string;
    'abAxisLabel'?: string;
    'abFadeName'?: string;
    'abFadeURL'?: string;
    'abMixHex'?: string;
    'abMixOpacity'?: string;
    'abTextPathHref'?: string;
    'abTextPathName'?: string;
    'acAxisLabel'?: string;
    'acTextPathHref'?: string;
    'acTextPathName'?: string;
    'axisLabelFontSize'?: number;
    'bHex'?: string;
    'bcAxisLabel'?: string;
    'bcTextPathHref'?: string;
    'bcTextPathName'?: string;
    'cFadeEndHex'?: string;
    'cFadeEndOpacity'?: string;
    'cFadeName'?: string;
    'cFadeURL'?: string;
    'cHex'?: string;
    'circleRadius'?: number;
    'corners'?: {"A":{"X","Y"}, "B":{"X","Y"},"C":{"X","Y"}};
    'hectagonHex'?: string;
    'recordArray'?: Array<{"A","B","C","X"?,"Y"?,"Z"?,"Label"}>;
    'showHectagon'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DashboardElementContainer': Components.DashboardElementContainer;
    'TernaryGraph': Components.TernaryGraph;
  }

  interface StencilIntrinsicElements {
    'dashboard-element-container': Components.DashboardElementContainerAttributes;
    'ternary-graph': Components.TernaryGraphAttributes;
  }


  interface HTMLDashboardElementContainerElement extends Components.DashboardElementContainer, HTMLStencilElement {}
  var HTMLDashboardElementContainerElement: {
    prototype: HTMLDashboardElementContainerElement;
    new (): HTMLDashboardElementContainerElement;
  };

  interface HTMLTernaryGraphElement extends Components.TernaryGraph, HTMLStencilElement {}
  var HTMLTernaryGraphElement: {
    prototype: HTMLTernaryGraphElement;
    new (): HTMLTernaryGraphElement;
  };

  interface HTMLElementTagNameMap {
    'dashboard-element-container': HTMLDashboardElementContainerElement
    'ternary-graph': HTMLTernaryGraphElement
  }

  interface ElementTagNameMap {
    'dashboard-element-container': HTMLDashboardElementContainerElement;
    'ternary-graph': HTMLTernaryGraphElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
